# This file generates the GitHub Actions matrix.
---
include:
  - board: nice_nano_v2
    shield: orcishcrafts1_left
    snippet: zmk-usb-logging studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: orcishcrafts1_right
    snippet: zmk-usb-logging studio-rpc-usb-uart

  - board: nice_nano_v2
    shield: settings_reset
