---
include:
  - board: nice_nano_v2
    shield: orcishcrafts1_left
    snippet: zmk-usb-logging # THE NATIVE FIX: Initializes logging specifically on the left side
  - board: nice_nano_v2
    shield: orcishcrafts1_right
  - board: nice_nano_v2
    shield: settings_reset
