# Core Matrix Hooks
CONFIG_KSCAN=y
CONFIG_GPIO=y
CONFIG_ZMK_STUDIO=y
CONFIG_ZMK_EXT_POWER=y

# Actively enable the standard low-level Zephyr SPI master engine
CONFIG_SPI=y

# Turn on display hardware driver pipelines inside the build system
CONFIG_DISPLAY=y
CONFIG_ST7789V=y

# Isolate the hardware entirely from high-level ZMK display managers
CONFIG_ZMK_DISPLAY=n
CONFIG_LVGL=n
