# Force internal oscillator clock synchronization for SuperMini clone boards
CONFIG_CLOCK_CONTROL_NRF_K32SRC_RC=y
CONFIG_CLOCK_CONTROL_NRF_K32SRC_250PPM=y

# Core Keyboard Electronic Options
CONFIG_KSCAN=y
CONFIG_GPIO=y
CONFIG_ZMK_EXT_POWER=y

# Disable graphics display engines completely
CONFIG_ZMK_DISPLAY=n

# THE UNIFIED POWER MANAGEMENT OVERRIDES
# Both parameters must be active together to unlock the low-level soft-off macro engine.
CONFIG_ZMK_SLEEP=y
CONFIG_ZMK_IDLE_TIMEOUT=30000
CONFIG_ZMK_PM_SOFT_OFF=y
