# Force low-level Nordic chip compilation to release NFC pins
CONFIG_NFCT_PINS_AS_GPIOS=y
# Enable ZMK Studio integration
CONFIG_ZMK_STUDIO=y
CONFIG_USB_DEVICE_STACK=y
# Disable ZMK Studio security locking
CONFIG_ZMK_STUDIO_LOCKING=n

# Enable ZMK display framework
CONFIG_ZMK_DISPLAY=y

# Enable the specific Zephyr ST7789 display driver
CONFIG_ST7789V=y

# Optional: Set the backlight pin to high if you wired BLK to a GPIO pin (e.g., D5 / P0.24)
# If you wired BLK directly to VCC, you don't need this line.
CONFIG_ZMK_DISPLAY_BL_GPIO_PIN=24
